before_install:
  - gem update bundler

script:
  - "bundle exec ruby test/test.rb"
  - "bundle exec codeclimate-test-reporter"

branches:
  only:
    - master

rvm:
  - "1.9.3"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"

addons:
  code_climate:
    repo_token: 521d341f3320acda1902d0db0a3a92fb16b11ebfe3d5ab730218d4fc0fb3db13

sudo: false
